version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: todo-graphql:local
    container_name: todo-graphql-api
    environment:
      - NODE_ENV=production
      - PORT=4000
    ports:
      - "4000:4000"
    restart: unless-stopped
    # healthcheck to ensure service is up
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/graphql',res=>{process.exit(res.statusCode===400?0:1)})"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s 